#!/usr/bin/env python3
"""
Debug script for PDF import functionality
"""

import sys
import os

# Add the app directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), 'app'))

print("Testing xhtml2pdf import...")

try:
    import xhtml2pdf
    print("✅ xhtml2pdf imported successfully")
    print(f"xhtml2pdf version: {xhtml2pdf.__version__}")
except ImportError as e:
    print(f"❌ xhtml2pdf import failed: {e}")

print("\nTesting PDF conversion agent import...")

try:
    from app.services.pdf_conversion_agent import XHTML2PDF_AVAILABLE, GEMINI_AVAILABLE, pdf_agent
    print(f"✅ PDF conversion agent imported successfully")
    print(f"XHTML2PDF_AVAILABLE: {XHTML2PDF_AVAILABLE}")
    print(f"GEMINI_AVAILABLE: {GEMINI_AVAILABLE}")
    
    if XHTML2PDF_AVAILABLE:
        print("✅ xhtml2pdf is available for PDF conversion")
    else:
        print("❌ xhtml2pdf is not available")
        
except ImportError as e:
    print(f"❌ PDF conversion agent import failed: {e}")

print("\nTesting basic PDF conversion...")

if XHTML2PDF_AVAILABLE:
    try:
        import asyncio
        
        async def test_conversion():
            from app.services.pdf_conversion_agent import convert_html_to_pdf_async
            
            test_html = """
            <!DOCTYPE html>
            <html>
            <head>
            <style>
            body { font-family: Arial; font-size: 12pt; }
            </style>
            </head>
            <body>
            <h1>Test PDF</h1>
            <p>This is a test PDF generated by xhtml2pdf.</p>
            </body>
            </html>
            """
            
            pdf_bytes, filename = await convert_html_to_pdf_async(test_html, "debug_test.pdf")
            print(f"✅ PDF conversion successful")
            print(f"   PDF size: {len(pdf_bytes)} bytes")
            print(f"   Filename: {filename}")
            
            # Save the PDF
            with open("debug_test.pdf", "wb") as f:
                f.write(pdf_bytes)
            print(f"   PDF saved as: debug_test.pdf")
            
        asyncio.run(test_conversion())
        
    except Exception as e:
        print(f"❌ PDF conversion failed: {e}")
else:
    print("❌ Cannot test PDF conversion - xhtml2pdf not available")
