#!/usr/bin/env python3
"""
Test script for minimal PDF agent
"""

import asyncio
import sys
import os

# Add the current directory to the path
sys.path.append(os.path.dirname(__file__))

async def test_minimal_pdf_agent():
    """Test the minimal PDF agent"""
    
    print("🧪 Testing Minimal PDF Agent")
    print("=" * 50)
    
    # Import the minimal agent
    try:
        from minimal_pdf_agent import minimal_pdf_agent
        print("✅ Minimal PDF agent imported successfully")
    except ImportError as e:
        print(f"❌ Minimal PDF agent import failed: {e}")
        return False
    
    # Test basic HTML to PDF conversion
    print("\n3. Testing basic HTML to PDF conversion...")
    try:
        test_html = """
        <!DOCTYPE html>
        <html>
        <head>
        <style>
        body { 
            font-family: Arial, sans-serif; 
            font-size: 12pt; 
            margin: 20pt;
        }
        .title { 
            font-size: 18pt; 
            font-weight: bold; 
            text-align: center; 
            color: #2c3e50;
        }
        </style>
        </head>
        <body>
        
        <div class="title">ROI Performance Report</div>
        <p>This is a test PDF report generated by the Minimal PDF Agent.</p>
        
        </body>
        </html>
        """
        
        # Convert HTML to PDF
        pdf_bytes, filename = await minimal_pdf_agent.convert_html_to_pdf(test_html, "minimal_test_report.pdf")
        
        print(f"✅ Basic HTML to PDF conversion successful")
        print(f"   PDF size: {len(pdf_bytes)} bytes")
        print(f"   Filename: {filename}")
        
        # Save test PDF
        with open("minimal_test_report.pdf", "wb") as f:
            f.write(pdf_bytes)
        print(f"   Test PDF saved as: minimal_test_report.pdf")
        
    except Exception as e:
        print(f"❌ Basic HTML to PDF conversion failed: {e}")
        return False
    
    print("\n" + "=" * 50)
    print("✅ All minimal PDF agent tests completed successfully!")
    return True

async def main():
    """Main function"""
    try:
        success = await test_minimal_pdf_agent()
        if not success:
            print("\n❌ Some tests failed. Please check the errors above.")
            sys.exit(1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Test interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(main())
